### ISSUE TITLE
How do I run on macOS?

### ISSUE THREAD

**Issue by LakshK98** [chase/awrit#17]
I followed all steps and cmake --build build ran successfully and generated awrit.app in build/awrit/Release
In a kitty terminal I ran
`sudo open awrit.app `
It exits immediately with no output/error.

**Comment by chase** [comment]
My apologies, I should have included it in the README 😅 I'll leave this issue open until I update the README.

You can run it using: `./build/awrit/Release/awrit.app/Contents/MacOS/awrit`  
You should notice this is the same path as the final linking step from a build:
```
[1/1] Linking CXX executable awrit/Release/awrit.app/Contents/MacOS/awrit
```

You also shouldn't run it with `sudo`, that's not necessary and might cause things not to work correctly.

---

As a side note: It's bundled as an app because on macOS, Chromium Embedded Framework requires this specific directory structure by default. I'll change the structure to be simpler when I have more time.

**Comment by chase** [comment]
@LakshK98 I added the ability to install and run it in a much simpler way.

I also attempted to make the README more clear, but feel free to open another issue if you run into problems.
