### ISSUE TITLE
Why is only arm64 supported on Mac?

### ISSUE THREAD

**Issue by jcaffey** [chase/awrit#19]
```shell
CMake Error at CMakeLists.txt:50 (message):
  Only arm64 is supported on macOS
```

```shell
❯ uname -m
x86_64
```

I was so excited about this. What are the limitations to running on x86_64? Can I help?

**Comment by chase** [comment]
Hey @jcaffey, I don't have an Intel Mac so I didn't test it, so not a terribly good reason. You're welcome to add support for it with a PR.

Builds of CEF (Chromium Embedded Framework) support it, so it should work 🙂
Currently uses these builds:
https://cef-builds.spotifycdn.com/index.html

You'll need to update the CMake files to support it. Thanks for your interest in my little project.

**Comment by jcaffey** [comment]
> Hey @jcaffey, I don't have an Intel Mac so I didn't test it, so not a terribly good reason. You're welcome to add support for it with a PR.
> 
> Builds of CEF (Chromium Embedded Framework) support it, so it should work 🙂 Currently uses these builds: https://cef-builds.spotifycdn.com/index.html
> 
> You'll need to update the CMake files to support it. Thanks for your interest in my little project.

I hacked up CMakeLists just to see if it worked. I got it to work in kitty, but it was terribly slow / sluggish on scroll.
https://github.com/jcaffey/awrit/blob/main/CMakeLists.txt

I also tried in wezterm (which I think supports the correct graphics protocol .... maybe not) but had no luck there.

Cool project, I hope to see it grow!

**Comment by chase** [comment]
@jcaffey I'm not sure if it's slow because of poor rendering performance or not, since it seemed fine on both of my machines.

If it's not stuttering, but it just seems like it isn't scrolling very much relative to your input, you can try adjusting the amounts here:
https://github.com/chase/awrit/blob/main/awrit/input_event_handler.cc#L330-L337

I'm sure there's a better way to scale mouse wheel input, but it's basically transmitted as a series of "mouse wheel scrolls down/up" but without any sense of velocity I just set it to 10 :sweat_smile: 

wezterm needs to be configured to support Kitty graphics protocol and key protocol, it doesn't work out of the box.
