### ISSUE TITLE
build-essential:command not found

### ISSUE THREAD

**Issue by SureshPradhana** [chase/awrit#23]
When I attempt to use the command  `build-essential ninja-build cmake`, an error is being thrown indicating that build-essential is not a command . I followed the steps below to install the prerequisites:

- `sudo apt-get install build-essential`
- `sudo apt-get install ninja-build`
- `sudo apt-get install cmake`
Despite having installed the prerequisites, the issue still persis

**Comment by chase** [comment]
Indeed it isn't a command, but packages that are available on Ubuntu. Since there are seemingly endless variants on Linux with different package names and package managers, I don't provide steps for every distro.

Since it seems you're using a Debian or Ubuntu variant, it should work. Can you provide the exact errors you're encountering while building?

**Comment by chase** [comment]
> I am facing another issue. unable to navigate the web page using the mouse.

It's possible it has broken in newer versions of Kitty, I haven't upgraded in some time. Please make another issue for it and provide the version of Kitty you're using.

**Comment by SureshPradhana** [comment]
In Kitty version 0.21.2, mouse navigation is not working, while in the latest version, 0.29.2, it is functioning properly. Should I create an issue for this?

**Comment by chase** [comment]
Ah, that is quite an old version.

I'm not sure what minimum version of Kitty is required to be honest, but I'm currently using 0.28.1.

I'll edit the README to state that as the minimum version. Thank you for helping
